### ISSUE TITLE
can not debug ansys UPF

### ISSUE THREAD

**Issue by fei-mao** [dutitello/debug-ansys-upf#2]
Hi, Doctor  @dutitello 
    I am a mechanical engineer using Ansys. Recently, I've been learning Ansys UPF, but trapped with some strange errors. If it's convenient for you to help, here's the details.
1)My test version is ANSYS2019R1, which is v193, and VS 2015/ Intel Fortran 17.04 which is exactly same as ANSYS help demands.
2)I take the origin ANSCUST.BAT and modify it as below like others, and add "-debug" in ansys.lrf. Compile this usermat3D2.F, it shows the warning "LNK4009, can not find PDB vfansys.pdb ……“
3）Link successed at last. But apdl output window does not show the comments1 in upf , neither the comments 2 in outfile.
4) Initially, i didn't consider debug mode but normal compile. The results were same, which ANSYS.exe can not output message from UPF file.
5)I even tried the new vesion Ansys2022R1, it's the same error——customized ANSYS.exe worked but can not output message and can not debug.
6) I have set the SMP, and it can not work.
7)My laptop is AMD Ryzen processor not intel one. Is this the reason?
8) I have learn your excellent post about this ansys upf topic, and I have tried your v195anscust.bat, but it's not suitable for v193. I am so glad if u can help.
[ANSCUST.TXT](https://github.com/dutitello/debug-ansys-upf/files/8680332/ANSCUST.TXT)
![anscust_modify](https://user-images.githubusercontent.com/76240685/168107823-0179c347-f4a4-45a2-9067-c20e809f14ab.png)
![ansyslrf_modify](https://user-images.githubusercontent.com/76240685/168107970-cf71e9d4-65ba-460f-815c-b8faf914c7ef.png)
[usermat3D2Fortran.txt](https://github.com/dutitello/debug-ansys-upf/files/8680373/usermat3D2Fortran.txt)
![Fortran add comments2](https://user-images.githubusercontent.com/76240685/168108861-35430e3b-aae0-4627-ac2c-59a2d8a07f33.png)
![compiling warning](https://user-images.githubusercontent.com/76240685/168110141-5873f747-0d4a-4592-8372-6b4564e604da.png)
![VS info](https://user-images.githubusercontent.com/76240685/168115703-d3364702-e80b-452f-a96a-6cff1858d71c.png)
![APDL Output Window wo Hi](https://user-images.githubusercontent.com/76240685/168116072-480e4544-2b4a-4dcd-973c-9ab6
![Output file wo comments2](https://user-images.githubusercontent.com/76240685/168116500-800f104e-7eda-4bcf-889c-f2d44420de0d.png)
13c45e55.png)
![windows info](https://user-images.githubusercontent.com/76240685/168117863-01154f37-5998-4680-be83-1e97b4d50e35.png)
![SMP Setting](https://user-images.githubusercontent.com/76240685/168118789-fa752c0c-51ff-4644-93d9-67a4c387dbcd.png)

**Comment by dutitello** [comment]
Hi @fei-mao,

Compiling custom Ansys executable for debugging will generate a lot of "LNK4009, can not find PDB" because the only PDB file that will exists is the one that you are now compiling (usermat). Don't you worry, this isn't a problem. 

Since your breakpoints are still red after connecting Visual Studio debugger to Ansys I would say that your compilation is ok.

Based on your usermat file name (usermat3d2.f), I believe that maybe there are 2 fortran files with usermat3d subroutines. Did you tried to delete the other usermat files and call yours as usermat.f?

**Comment by fei-mao** [comment]
Hi Doctor dutitello,
Too much thanks for your timely reply. I tried to move the example .F to other unrelevant directory and change my usermat name as usermat.f, and I even delete the install directory .F files, and it worked finally. 
You really helped a lot, thanks so much again! @dutitello

**Comment by dutitello** [comment]
I'm glad it worked! 
Good luck on your research.
